### ISSUE TITLE
Some times the subtitles have a bad encoding

### ISSUE THREAD

**Issue by gilgamezh** [touchandgo-devs/touchandgo#30]

**Comment by gargamel007** [comment]
I'm having the same issues with french subtitles files that get corrupted when converted to UTF8 by subliminal 0.7.5.
Actually I managed to reproduce the issue on chardet 2.3.0 : chardet identifies my file as a Windows-1255 where it should be Latin1 encoding (confirmed using vim). When converting to utf8 I get the same scrambled accents as the version downloaded by subliminal.

Is there an option to force subliminal not to change the encoding of files downloaded ? 
It might be a quick fix as my TV can read the original file without any issues.

**Comment by felipelerena** [comment]
Fixed in the devel branch
