### ISSUE TITLE
Dependencias prioritarias?

### ISSUE THREAD

**Issue by aarondiazr** [touchandgo-devs/touchandgo#67]
Hola, me interesa mucho su proyecto, quiero implementar una interfaz gráfica, he revisado el código, pero quiero saber cuales son las dependencias que necesita de python para buscar y descargar subtitulos y vídeos, es decir, sin tomar en cuenta las del server para hacer streaming!

Por cierto muy buen proyecto, lo conocí porque vi el día de ayer una charla en youtube sobre esto!

**Comment by felipelerena** [comment]
hola, ya tenemos interfaz grafica. Tenés que correr el comando tsproxy.
Las dependencias estan en el archivo requirements y en el setup.py

**Comment by aarondiazr** [comment]
jeje gracias, pero me gustaria hacer mi interfaz :)

**Comment by gilgamezh** [comment]
Hola! Gracias por el interes :smile: 
Para que descargue el torrent sin hacer streaming deberías cambiar una gran parte del código. Ya que la lógica más compleja está en el streaming

En el archivo de requeriments está todo lo que usamos. Puntualmente para buscar torrents y subtitulos tenes que usar las librerias que nombramos en la charla. torrentmediasearch y sublime

Si te llega a interesar la parte del stream y necesitas algún cambio [ara integrarte dejanos un ticket :rocket: 

De nuestra parte nos interesa segur trabajando con la interfaz web.

**Comment by felipelerena** [comment]
eh... hace lo que quieras, yo te recomiendo enfocar los esfuerzos en lo que hay en vez de armar _otra_ UI... pero es tu tiempo :D

**Comment by aarondiazr** [comment]
Gracias gilgamezh, si quiero hacer streaming pero de una manera mas eficiente que solo usando Flask como UI, lo que veo es que el código no esta preparado para ser usado de manera tan modular, pero lo voy a desmenuzar, también voy a cambiar subliminal para obtener resultados en español de otros sitios, porque se queda corto!

**Comment by gilgamezh** [comment]
@aarondiazr Tenemos mucho que mejorar en eso. 
De todos modos a la clase DownloadManager le podés pasar un magnet directamente. Luego el manejo del subtitulo lo podes hacer en el player que definas. O simplemente no pedirlo y manejarlo en la UI :wink:

**Comment by felipelerena** [comment]
En cuanto a los subtitulos la otra opcion es que le agregues fuentes a
subliminal de esa manera mejoras subliminal y colaboras con un proyecto que
usa un monton de gente.
En cuanto a la descarga podes hacer tu propia clase de busqueda, tu propia
clase de player y tu propia clase de subtitulos y seguir usando el motor y
la estrategia.

Con respecto al tema UI no es el objetivo del proyecto tener una UI tipo
popcorn time (aun).

Saludos,
Lipe


Lipe
twitter @felipelerena

2015-01-28 18:12 GMT-03:00 Nicolás Demarchi <notifications@github.com>:
