### ISSUE TITLE
Nueva Fuente de Subtitulos

### ISSUE THREAD

**Issue by aarondiazr** [touchandgo-devs/touchandgo#68]
Bueno, pues como les comentaba, los subtitulos son importantes, asi que me he dado a la tarea de buscar el mejor sitio para ello y luego encontre un pequeño script que hacia web scraping a dicho sitio, aunque dejo de funcionar, pero ya lo he arreglado, pueden probar y es bastante bueno!

https://github.com/aarondiazr/Subtitulos.py

**Comment by gilgamezh** [comment]
@aarondiazr hola! 
Honestamente la idea es que sirva para todos los idiomas. Estaría re bueno poder agregar soporte para subtitulos.es a subliminal.
Ni hablar de argenteam!
