### ISSUE TITLE
[windows support] replace blessing with colorama

### ISSUE THREAD

**Issue by zodman** [touchandgo-devs/touchandgo#77]
well i want windows support 

so the core (touchandgo/download at least) must work with windows some modules not support windows plataforms

replace:

blessing with colorama

**Comment by felipelerena** [comment]
Sorry we will not do that.

**Comment by zodman** [comment]
fork!!!!!!!!!!!!!11

**Comment by felipelerena** [comment]
I'm OK if you fork the project. But maybe it will be more useful if you help the blessings guys fix this issue https://github.com/erikrose/blessings/issues/21
